INSERT INTO `members` (`member_id`,
                       `member_uuid`,
                       `member_name`,
                       `email_address`,
                       `nickname`,
                       `introduce`,
                       `sns_url`,
                       `phone_number`,
                       `profile_url`,
                       `level_id`,
                       `member_state_code`,
                       `role_type_code`,
                       `black_member_yn`,
                       `password`,
                       `password_history`,
                       `password_wrong_count`,
                       `last_login_datetime`,
                       `created_datetime`,
                       `create_member_id`,
                       `updated_datetime`,
                       `update_member_id`)
VALUES (1, '96553400-35e3-45a3-9078-04ae4a53c452', 'test1', 'test_member1@lgcns.com', 'test1', '나는 test1',
        'https://www.instagram.com/test1/', '010-1230-0001', '/PROFILE/SYSTEM/sample_1.png', 1, 'NORMAL', 'BASIC', 'N',
        NULL, NULL, 0, NULL, NOW(), -1, NOW(), -1),
       (2, 'b1ff9cad-2c42-4afc-93c7-fd0124838bdb', 'test2', 'test_member2@lgcns.com', 'test2', '나는 test2',
        'https://www.instagram.com/test2/', '010-1230-0002', '/PROFILE/SYSTEM/sample_2.png', 1, 'WITHDRAWAL', 'BASIC',
        'Y', NULL, NULL, 0, NULL, NOW(), -1, NOW(), -1),
       (3, '9dbb22bb-8916-47d7-8ec9-987df198282d', 'test3', 'test_member3@lgcns.com', 'test3', '나는 test3',
        'https://www.instagram.com/test3/', '010-1230-0003', '/PROFILE/SYSTEM/sample_3.png', 1, 'NORMAL', 'BASIC', 'N',
        NULL, NULL, 0, NULL, NOW(), -1, NOW(), -1),
       (4, '908544ec-4870-4086-ae5c-16afee0334d4', 'test4', 'test_member4@lgcns.com', 'test4', '나는 test4',
        'https://www.instagram.com/test4/', '010-1230-0004', '/PROFILE/SYSTEM/sample_4.png', 1, 'NORMAL', 'BASIC', 'N',
        NULL, NULL, 0, NULL, NOW(), -1, NOW(), -1),
       (5, '6eb3bc8e-ad54-42f9-b40e-2be97e62b632', 'test5', 'test_member5@lgcns.com', 'test5', '나는 test5',
        'https://www.instagram.com/test5/', '010-1230-0005', '/PROFILE/SYSTEM/sample_5.png', 1, 'HALT', 'BASIC', 'N',
        NULL, NULL, 0, NULL, NOW(), -1, NOW(), -1)
;