## SET HTTPS
server:
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password:
    key-alias: spring
  port: 8443

##  SET HTTP2
#  http2:
#    enabled: true

## Logging
logging:
  level:
    com.kane.kanebe: DEBUG
#    redis.clients: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
